'use client';
import { saveImage } from '@/db_mongo/actions';
import { formOpenAI } from '@/types';
import { useTransition } from 'react';
import { useSession, signIn, signOut } from 'next-auth/react';
import { match, P } from 'ts-pattern';
import Image from 'next/image';
import { redirect } from 'next/dist/server/api-utils';
// import { useRouter } from 'next/router';

export default function ImageGenerated({
	photo_url,
	prompt,
	user_name,
}: formOpenAI) {
	let [isPending, startTransition] = useTransition();
	const { data, status } = useSession();
	// const route = useRouter();

	return (
		<div className='shadow-md'>
			<div className='mx-auto flex-col bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
				<img
					placeholder='blur'
					className='w-full h-full object-contain'
					width={300}
					height={300}
					src={photo_url!}
					alt={'image generated'}
				/>
				{data?.user && (
					<div className='text-center'>Generated by {data?.user.name}</div>
				)}
			</div>
			{/* if is logged the user can save the image */}
			<div className='text-center'>
				{match(status)
					.with('loading', () => (
						<div className='animate-pulse'>Loading....</div>
					))
					.with('authenticated', () => (
						<button
							type='button'
							className='border shadow-md px-2 py-1 rounded-md active:translate-y-[1px]'
							disabled={isPending}
							onClick={() =>
								startTransition(async () => {
									try {
										await saveImage({ photo_url, prompt, user_name });
										console.log('saved!');
									 
										// route.push('/collections');
									} catch {
										console.log('save failed');
									}
								})
							}
						>
							Save image
						</button>
					))
					.with('unauthenticated', () => (
						<button
							type='button'
							className='border shadow-md px-2 py-1 rounded-md active:translate-y-[1px]'
							disabled={isPending}
							onClick={() => signIn('google')}
						>
							Login to save your images
						</button>
					))
					.exhaustive()}
			</div>
		</div>
	);
}
