'use client';
import { formOpenAI } from '@/types';
import { AnimatePresence, Variants, motion } from 'framer-motion';
import { useStore } from '@/store';
import { useEffect, useState, useTransition } from 'react';
import { deleteItems, saveImage } from './action_mongoDB';

export default function ImageGenerated(props: formOpenAI) {
	const { photo_url, user_name, prompt } = props;
	const [rendered, setRenderer] = useState<boolean>(false);
	let [isPending, startTransition] = useTransition();

	return (
		<div>
			{!!photo_url && (
				<>
					<div className='mx-auto bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
						<img
							placeholder='blur'
							className='w-full h-full object-contain'
							width={300}
							height={300}
							src={photo_url}
							alt={'image generated'}
						/>
					</div>
					{!!user_name && (
						<div className='text-center'>Generated by {user_name}</div>
					)}
					<div className='text-center'>
						<button
							type='button'
							className='border shadow-md px-2 py-1 rounded-md active:translate-y-[1px]'
							onClick={() => startTransition(() => saveImage(props))}
						>
							save{' '}
						</button>
					</div>
				</>
			)}
		</div>
	);
}
