"use client";
import { saveImage } from "@/db_mongo/actions";
import { formOpenAI } from "@/types";
import { useState, useTransition } from "react";
import { useSession, signIn, signOut } from "next-auth/react";
import { match, P } from "ts-pattern";
import { downloadImage } from "@/helpers";
import Link from "next/link";
import useSWR, { SWRConfig } from "swr";

export default function ImageGenerated({
  photo_url,
  prompt,
  user_name,
}: formOpenAI) {
  const { data, status } = useSession();
  const [saved, setSaved] = useState(false);
  if (!photo_url) return null;

  return (
    <div className="shadow-md">
      <div className="mx-auto flex h-64 w-64 flex-col items-center justify-center rounded-lg border border-gray-300 bg-gray-50 p-3 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500">
        <img
          placeholder="blur"
          className="h-full w-full object-contain"
          width={300}
          height={300}
          src={photo_url!}
          alt={"image generated"}
        />
        {data?.user && (
          <div className="text-center">Generated by {data?.user.name}</div>
        )}
      </div>
      {/* if is logged the user can save the image */}
      <div className="text-center">
        <button
          className="rounded-md border px-2 py-1 shadow-md active:translate-y-[1px]"
          onClick={() => downloadImage({ photo_url })}
        >
          Download
        </button>
        {match(status)
          .with("authenticated", () =>
            saved ? (
              <div>Saved!</div>
            ) : (
              <button
                type="button"
                className="rounded-md border px-2 py-1 shadow-md active:translate-y-[1px]"
                disabled={saved}
                onClick={() => {
                  // async () => {
                  //   try {
                  //     const result = await saveImage({
                  //       photo_url,
                  //       prompt,
                  //       user_name,
                  //     });
                  //     result && setSaved(true);
                  //     console.log(result);
                  //   } catch {
                  //     console.log("save failed");
                  //   }
                  // };
                }}
              >
                Save image
              </button>
            )
          )
          .with("loading", () => (
            <div className="animate-pulse">Loading....</div>
          ))
          .with("unauthenticated", () => (
            <button
              type="button"
              className="rounded-md border px-2 py-1 shadow-md active:translate-y-[1px]"
              disabled={saved}
              onClick={() => signIn("google")}
            >
              Login to save your images
            </button>
          ))
          .exhaustive()}
      </div>
    </div>
  );
}
