'use client';
import { saveImage } from '@/db_mongo/actions';
import { formOpenAI } from '@/types';
import { useState, useTransition } from 'react';

export default function ImageGenerated(props: formOpenAI) {
	const { photo_url, user_name, prompt } = props;
	let [isPending, startTransition] = useTransition();

	return (
		<div>
			{!!photo_url && (
				<>
					<div className='mx-auto bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
						<img
							placeholder='blur'
							className='w-full h-full object-contain'
							width={300}
							height={300}
							src={photo_url}
							alt={'image generated'}
						/>
					</div>
					{!!user_name && (
						<div className='text-center'>Generated by {user_name}</div>
					)}
					{/* if is logged can save the image */}
					<div className='text-center'>
						<button
							type='button'
							className='border shadow-md px-2 py-1 rounded-md active:translate-y-[1px]'
							disabled={isPending}
							onClick={() =>
								startTransition(async () => {
									try {
										await saveImage(props);
										console.log('saved!');
									} catch {
										console.log('save failed');
									}
								})
							}
						>
							save{' '}
						</button>
					</div>
				</>
			)}
		</div>
	);
}
